name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]  # keep a single Python version for Playwright

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-playwright playwright allure-pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright Browsers
        run: |
          playwright install --with-deps

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run single test with pytest + Playwright
        run: pytest python_auto/test_chatbot_systemslot_assign.py --alluredir=reports/allure-results


      # Install Allure CLI for report generation
      - name: Install Allure CLI
        run: |
          curl -o allure-2.27.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          sudo tar -zxvf allure-2.27.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: allure generate reports/allure-results --clean -o reports/allure-report

      # Deploy the report to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./reports/allure-report


      # Send email with public URL instead of attachment
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Test Result"
          to: mmaliknadeem11@gmail.com
          from: GitHub Actions <testing1mna@gmail.com>
          body: |
            The test case has completed ✅

            View the Allure report here:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

            
